### ISSUE TITLE
NAN issue in powf() expression causes compressor to not let audio thru

### ISSUE THREAD

**Issue by mike6000** [MarkzP/AudioEffectDynamics#1]
The powf expression may return NAN (Not A Number) if the audio level in is low from a source it seems. Then the compressor will not give audio data out and appears "dead" ... 

Here: https://github.com/MarkzP/AudioEffectDynamics/blob/dc15c5c055059835a9f5c6f37cb0be8ba13288d3/effect_dynamics.cpp#L122

To check if a NAN_ https://stackoverflow.com/questions/570669/checking-if-a-double-or-float-is-nan-in-c/570694

I added this "hacky" fix:

 if (compdb != compdb) compdb = 0.0f; // trick to detect NAN  .. Became a bit overmodulated with compdb to 1 so I set it to 0

I am not sure if it is a good idea to set it to zero however. At least this fixed the NAN issue.

**Comment by MarkzP** [comment]
Good catch!
I have updated this repo with my latest working copy, which includes a different fix since I refactored a few things some time ago. It's more efficient & appears to be quite stable now
