### ISSUE TITLE
Version for Teensy 3.2 

### ISSUE THREAD

**Issue by FrankBoesing** [MarkzP/AudioEffectDynamics#9]
Can you add a float-less version for Teensys without FPU?

**Comment by MarkzP** [comment]
At the moment, the T4.0 is 20¢ (cdn$) more than the T3.2:
[https://www.robotshop.com/ca/en/teensy-32-usb-microcontroller-development-board.html](url)
[https://www.robotshop.com/ca/en/teensy-40-usb-microcontroller-development-board.html](url)

Spoiled as I am with the power of the T4, I would say that I'm not too keen to spend much time on an all-interger version.
In fact, my plans are to port it to the elusive 32bit float version of the Audio Library, if it ever becomes official

Marc

**Comment by FrankBoesing** [comment]
I don't think it becomes official - chance are pretty low to get this merged if it needs a FPU and is slow on older Teensys.
